server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://users-service
          predicates:
            - Path=/auth/**
        # USERS PATHS
          # PRIVATES
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        # BOOKINGS PATHS
          # PRIVATES
        - id: bookings-service
          uri: lb://products-service
          predicates:
            - Path=/bookings/**
          filters:
            - AuthFilter
        # CATEGORIES PATHS
          # PRIVATES
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/categories/save/new
            - Path=/categories/find/ids
            - Path=/categories/update/category
            - Path=/categories/delete/**
          filters:
            - AuthFilter
          # PUBLICS
        - id: categories-service-public
          uri: lb://categories-service
          predicates:
            - Method=GET
        # CITIES PATHS
          # PRIVATES
        - id: cities-service
          uri: lb://cities-service
          predicates:
            - Path=/cities/save/new
            - Path=/cities/find/ids
            - Path=/cities/update/city
            - Path=/cities/delete/**
            - Path=/countries/**
          filters:
            - AuthFilter
          # PUBLICS
        - id: cities-service-public
          uri: lb://cities-service
          predicates:
            - Method=GET
        # FEATURES PATHS
          # PRIVATES
        - id: features-service
          uri: lb://features-service
          predicates:
            - Path=/features/**
          filters:
            - AuthFilter
        # IMAGES PATHS
          # PRIVATES
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images/save/new
            - Path=/images/find/ids
            - Path=/images/save/collection
            - Path=/images/update/**
            - Path=/images/delete/**
          filters:
            - AuthFilter
          # PUBLICS
        - id: images-service-public
          uri: lb://images-service
          predicates:
            - Method=GET       
        # SPECS PATHS
          # PRIVATES
        - id: specs-service
          uri: lb://specs-service
          predicates:
            - Path=/specs/**
          filters:
            - AuthFilter
        # PRODUCTS PATHS
          # PRIVATES
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/save/new
            - Path=/products/update/product
            - Path=/products/delete/**
          filters:
            - AuthFilter
          # PUBLICS
        - id: products-service-publics
          uri: lb://products-service
          predicates:
            - Method=GET