server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: lb://users-service
          predicates:
            - Path=/auth/**
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/users/**
          filters:
            - AuthFilter
        - id: bookings-service
          uri: lb://products-service
          predicates:
            - Path=/bookings/**
          filters:
            - AuthFilter
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/categories/**
          filters:
            - AuthFilter
        - id: cities-service
          uri: lb://cities-service
          predicates:
            - Path=/cities/**
          filters:
            - AuthFilter
        - id: features-service
          uri: lb://features-service
          predicates:
            - Path=/features/**
          filters:
            - AuthFilter
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images/**
          filters:
            - AuthFilter
        - id: specs-service
          uri: lb://specs-service
          predicates:
            - Path=/specs/**
          filters:
            - AuthFilter
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
          filters:
            - AuthFilter
