server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/categories/**
        - id: cities-service
          uri: lb://cities-service
          predicates:
            - Path=/cities/**
        - id: features-service
          uri: lb://features-service
          predicates:
            - Path=/features/**
        - id: images-service
          uri: lb://images-service
          predicates:
            - Path=/images/**
        - id: specs-service
          uri: lb://specs-service
          predicates:
            - Path=/specs/**
