server:
  port: 9000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    instance:
      hostname: localhost 

resilience4j.circuitbreaker:
  instances:
    allServicesCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10   
    usersServicesCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 8s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10   