USE digitalRentcarFeatures;

-- Sprint II
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '145 HP', 7);
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '7', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Diesel', 8);   
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '455 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '310 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '283 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '480 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '200 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '122 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '85 HP', 7);    
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '5', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '204 HP', 7);   
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5);
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '5', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Diesel', 8);
-- INSERT INTO features (name, value, image_id) VALUES ('enginePower', '98 HP', 7);
-- INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5);
-- INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
-- INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Electrico', 6);

INSERT INTO features (id, name, value, image_id) VALUES (1, 'enginePower', '145 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (2, 'airConditioning', 'true', 5); 
INSERT INTO features (id, name, value, image_id) VALUES (3, 'seats', '7', 9);
INSERT INTO features (id, name, value, image_id) VALUES (4, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (5, 'enginePower', '455 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (6, 'airConditioning', 'false', 5);
INSERT INTO features (id, name, value, image_id) VALUES (7, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (8, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (9, 'enginePower', '310 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (10, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (11, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (12, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (13, 'enginePower', '283 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (14, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (15, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (16, 'combustible', 'Gasolina', 8); 
INSERT INTO features (id, name, value, image_id) VALUES (17, 'enginePower', '480 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (18, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (19, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (20, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (21, 'enginePower', '200 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (22, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (23, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (24, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (25, 'enginePower', '122 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (26, 'airConditioning', 'false', 5);
INSERT INTO features (id, name, value, image_id) VALUES (27, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (28, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (29, 'enginePower', '85 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (30, 'airConditioning', 'false', 5);
INSERT INTO features (id, name, value, image_id) VALUES (31, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (32, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (33, 'enginePower', '204 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (34, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (35, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (36, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (37, 'enginePower', '98 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (38, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (39, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (40, 'combustible', 'Electrico', 6);
INSERT INTO features (id, name, value, image_id) VALUES (41, 'enginePower', '147 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (42, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (43, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (44, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (45, 'enginePower', '192 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (46, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (47, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (48, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (49, 'enginePower', '153 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (50, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (51, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (52, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (53, 'enginePower', '186 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (54, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (55, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (56, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (57, 'enginePower', '180 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (58, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (59, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (60, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (61, 'enginePower', '165 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (62, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (63, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (64, 'combustible', 'Electrico', 6);
INSERT INTO features (id, name, value, image_id) VALUES (65, 'enginePower', '275 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (66, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (67, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (68, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (69, 'enginePower', '150 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (70, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (71, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (72, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (73, 'enginePower', '224 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (74, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (75, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (76, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (77, 'enginePower', '180 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (78, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (79, 'seats', '5', 9);
INSERT INTO features (id, name, value, image_id) VALUES (80, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (81, 'enginePower', '181 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (82, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (83, 'seats', '2', 9);
INSERT INTO features (id, name, value, image_id) VALUES (84, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (85, 'enginePower', '382 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (86, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (87, 'seats', '4', 9);
INSERT INTO features (id, name, value, image_id) VALUES (88, 'combustible', 'Gasolina', 8);
INSERT INTO features (id, name, value, image_id) VALUES (89, 'enginePower', '132 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (90, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (91, 'seats', '7', 9);
INSERT INTO features (id, name, value, image_id) VALUES (92, 'combustible', 'Diesel', 8);
INSERT INTO features (id, name, value, image_id) VALUES (93, 'enginePower', '245 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (94, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (95, 'seats', '8', 9);
INSERT INTO features (id, name, value, image_id) VALUES (96, 'combustible', 'Electrico', 6);
INSERT INTO features (id, name, value, image_id) VALUES (97, 'enginePower', '280 HP', 7);
INSERT INTO features (id, name, value, image_id) VALUES (98, 'airConditioning', 'true', 5);
INSERT INTO features (id, name, value, image_id) VALUES (99, 'seats', '8', 9);
INSERT INTO features (id, name, value, image_id) VALUES (100, 'combustible', 'Gasolina', 8);
