USE digitalRentcarFeatures;

INSERT INTO features (name, value, image_id) VALUES ('enginePower', '145 HP', 7);
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
INSERT INTO features (name, value, image_id) VALUES ('seats', '7', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Diesel', 8);   
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '455 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '310 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '283 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '480 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '200 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5); 
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '122 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '85 HP', 7);    
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'false', 5);
INSERT INTO features (name, value, image_id) VALUES ('seats', '5', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Gasolina', 8); 
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '204 HP', 7);   
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5);
INSERT INTO features (name, value, image_id) VALUES ('seats', '5', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'diesel', 8);
INSERT INTO features (name, value, image_id) VALUES ('enginePower', '98 HP', 7);
INSERT INTO features (name, value, image_id) VALUES ('airConditioning', 'true', 5);
INSERT INTO features (name, value, image_id) VALUES ('seats', '4', 9);
INSERT INTO features (name, value, image_id) VALUES ('combustible', 'Electrico', 6);