USE digitalRentcarProducts;

-- Products
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (1, 'Chevrolet Captiva', 'Captiva Turbo llega para desafiar todas las expectativas de lo que se espera de un SUV. Más allá de su atractivo diseño, tiene el espacio suficiente para todo y todos, gracias a su capacidad para 5 o 7 pasajeros. Está equipada con tecnología superior y atributos avanzados de seguridad.', 1, 1, 1);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (2, 'Honda CRVs', 'Diseñado para llevarte más lejos, El CR-V ofrece millas y millas de diversión al conducir, con tracción total, 212 caballos de fuerza en total del sistema, y con mucho espacio de carga. Su exterior deportivo cuenta con líneas esculpidas y rines de aleación de 19 pulgadas disponibles, mientras que su espacio interior ofrece uun volante con calefacción disponible, asientos tapizados en cuero y otros materiales premium.', 1, 1, 6);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (3, 'Kia Soul', 'Su caracteristica forma cuadrada ofrece mucho espacio para que cuatro adultos naveguen cómodamente, junto a un área de carga suficientemente grande para guardar todo el equipo y maletas durante su viaje. El KIA Soul nos ofrece iluminación ambiental, una plataforma de carga para teléfonos inteligentes, una pantalla de visualización frontal, encendido por botón con entrada sin llave y calefacción para los asientos y el volante.', 1, 1, 11);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (4, 'Jeep Renegade', 'El Renegade es un punto de entrada para la marca de estilo de vida y una alternativa resistente a la mayoría de los SUV subcompactos. Si arrojarse al barro y trepar por las rocas no es una rutina, no importa, sus adornos apesar de no estar clasificados para senderos son igual de resistentes a que si lo estuvieran, tiene uno de los interiores más espaciosos del segmento, permitiendo viajes relajantes junto a una lista de asistencias estándar y de gran ayuda para el conductor.', 1, 1, 15);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (5, 'Ford Escape', 'Uno de los SUVs favoritos por excelencia con muchas sutilezas, accesorios y detalles incluidos entre ellos, sensores de estacionamiento traseros, configuraciones de memoria para el asiento del conductor y los espejos exteriores, tapicería de cuero sintético, una función de arranque remoto, un volante forrado en cuero con calefacción, un sensor de apertura para la trasera, luces antiniebla y rieles laterales en el techo, son algunas de las comodidas que te brindara esta magnifica SUV.', 1, 1, 16);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (6, 'Nissan Versa', 'El sedán Nissan Versa es una excelente herramienta de transporte para llevar a los pasajeros del punto A al punto B, pero también hace que el viaje sea más agradable que muchos otros autos subcompactos. El Nissan no solo es atractivo, su motor de cuatro cilindros tiene una economía de combustible en las carreteras impresionante. El suave andar del Versa y los cómodos asientos delanteros lo convierten en un carro relajante para los desplazamientos diarios, y está disponible con más asistencia al conductor que sus compañeros de clase.', 2, 1, 7);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (7, 'Honda Accord', 'El Accord combina un perfil elegante y líneas de carrocería fluidas con un interior lleno de características, que logra un sedán con el equilibrio perfecto entre forma y función. Entre sus caracteristicas nos ofrece estilo y espacio para cinco personas, con una increíble cantidad de espacio trasero para la cabeza y las piernas. Los asientos tapizados en cuero disponibles realzan la experiencia de lujo, despidase de los cables el cargador inalambrico proporciona un facil acceso a su telefono en todo momento.', 2, 1, 12);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (8, 'Toyota Vios', 'Toyota ha declarado explícitamente que, con el modelo Toyota Vios, se han propuesto conservar las mejores cualidades que los clientes han llegado a conocer, amar, a saber, la calidad y la comodidad. Fieles a su palabra, parecen estar en el camino correcto con la nueva generación. más equipamiento, un interior más refinado y una caja de cambios completamente nueva, son propiedades del nuevo Toyota Vios, disponible en nuestras vitrinas. El Mazda3 se destaca como uno de los mejores vehículos en una clase altamente competitiva, con puntajes de seguridad de primer nivel y un rendimiento ágil', 2, 1, 10);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (9, 'Chevrolet Cruze', 'Este automovil nos ofrece gran espacio especialmente en el asiento trasero junto a un interior con cierto grado de lujo. El motor estándar es un turbo de cuatro cilindros y 1.4 litros con una transmisión manual o automática de seis velocidades. Una función de arranque-parada que reduce el uso de combustible. Las funciones de infoentretenimiento incluyen Apple CarPlay y Android Auto además invluye comandos de voz naturales a través de Siri o Google Now desde su teléfono, cuenta con asistencia para mantener el carril, asistente avanzado de parqueo, alerta de colisión frontal, iluminación inteligente, alerta de punto ciego e indicador de distancia del vehículo delantero', 2, 1, 13);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (10, 'Mazda 3', 'Este sedán deportivo es uno de los autos más divertidos de conducir en su clase y ofrece dirección dinámica, frenos sensibles y aceleración rápida. También tiene una conducción cómoda que suaviza la mayoría de las imperfecciones de la carretera. En el interior, el Mazda3 cuenta con un sistema de información y entretenimiento fácil de usar y hay materiales de lujo en toda su cabina.', 2, 1, 14);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (11, 'Chevrolet Camaro', 'El Chevrolet Camaro ofrece buen nivel de equipamiento y asistencias al conductor para que el viaje en ciudad y carretera sea más seguro, pero no deja de lado sus raíces deportivas y puede liberar todo su potencial cuando uno lo desee. Si eres fanático de los autos americanos, este muscle car es uno de los más fieles a su origen.', 3, 1, 2);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (12, 'Ford Mustang', 'Escucha el rugido de un Mustang cuando el suelo comienza a temblar y las piernas a agitarse. Como siempre, el Mustang invoca su desempeño con características de manejo mejorado, opciones de motor súper potente y diseño de Mustang clásico. El habitáculo del Ford Mustang cuenta con un diseño muy personal que aboga por las líneas curvas y la profusión de botones e interruptores, recordando enormemente a los salpicaderos que el propio Mustang ofrecía en los años 60 y 70.', 3, 1, 5);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (13, 'Hyundai Veloster', 'El Veloster un vehiculo deportivo de alto rendimiento, es la mejor opcion a la hora de querer un auto practico, con 275 caballos de fuerza y ​​un manejo que hace sonreír, el Veloster nos ofrece una experiencia unica a la hora de rodar ya sea en la ciudad o en una carretera con curvas. El diseño exclusivo de tres puertas del Veloster también lo hace un poco más práctico en comparación con aquellos de dos puertas.', 3, 1, 17);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (14, 'Mazda Mx-5', 'Llamar al Mazda MX-5 Miata un ícono automotriz no es exagerado, ya que su legado se remonta a más de 30 años y su comportamiento de conducción alegre siempre ha sido su atributo de carácter más fuerte. El motor de cuatro cilindros del Miata ofrece la potencia suficiente para que se sienta valiente además de su chasis perfectamente equilibrado, ideal para atravesar tramos con curvas de la carretera. La cabina del Miata es pequeña para dos y el espacio de carga es limitado, pero no fue hecho para viajes por carretera; Está diseñado para viajes enérgicos bañados por el sol y días de pista.', 3, 1, 21);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (15, 'Toyota Supra', 'El Toyota Supra es un deportivo biplaza japonés, de propulsión trasera y motor turboalimentado de seis cilindros. Se trata de un coche de carácter deportivo, un escaparate tecnológico para la marca, que nunca ha descuidado el confort a bordo o la utilización en el día a día. cuenta con un diseño exterior muy original en el que destacan las formas muy voluminosas de sus pasos de rueda posteriores. Además cuenta con un morro muy característico, un techo de doble burbuja y una zaga en la que destacan los pilotos y su alerón tipo “cola de pato”.', 3, 1, 22);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (16, 'Nissan Frontier', 'Durante generaciones, Nissan ha fabricado las pick ups más confiables, manteniéndose así siempre a la delantera en resistencia y durabilidad. Nissan NP300® está diseñada para satisfacer todas tus necesidades gracias a su motor, capacidad de carga y chasis reforzado ademas de sus extraordinarios ángulos de entrada (28.5°) y salida (23.6°) le permiten enfrentarse sin problema a terrenos inclinados  e inhóspitos.', 4, 1, 3);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (17, 'Toyota Hilux 2016', 'Bajo la musculosa y gran carrocería del Hilux se esconde un chasis tradicional de pick-up y vehículo todoterreno. Se trata de una plataforma de largueros y travesaños con suspensión trasera de ballesta diseñada especialmente para soportar grandes cargas, una gran capacidad off-road y una elevada versatilidad de carrocerías. La capacidad de carga de la caja permite hasta 1.040 kilogramos de carga. En función de la cabina puede albergar entre dos y cinco pasajeros, y en cuanto a cotas todoterreno ofrece 27 grados de ángulo de entrada, 27 grados de ángulo de salida y 23 grados de ángulo ventral con una profundidad de vadeo de hasta 70 centímetros con una altura libre de 29,3 centrímetros.', 4, 1, 9);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (18, 'Mitsubishi L200', 'El L200 está diseñado para enfrentarse a terrenos difíciles, con la comodidad de una berlina alemana, tiene tracción en las cuatro ruedas conmutable que se puede activar sobre la marcha. Esta cabina doble tiene un excelente consumo de combustible con cerca de dos toneladas de peso tiene recorridos de 700 a 800 km con su tanque de combustible de 75 litros, además de medidas de seguridad, desempeño integral y características electrónicas. Tiene una entrada sin llave, control de clima de doble zona y un excelente sistema de información y entretenimiento que es compatible con ApplePlay y Android Auto.', 4, 1, 18);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (19, 'Volkswagen Amarok', 'Una pickup resistente, confiable, comoda y con fuerza, asi podemos defiinir la Amarok, con un interior que combina con su exterior sumado a un fuerte y rugiente caracter bajo su capó. Gracias a su diseño este vehiculo se permite manejar ángulos y pendientes que te dejarian con la boca abierta. Su interior cuenta con mucho espacio para guardar todo lo que necesites en tus aventuras, asientos electricos con 14 movimientos y una lujosa tapiceria de cuero que te garantizan una conducción cómoda y un viaje seguro. Si lo que buscas es un 4WD de doble cabina que va por la ciudad como si de un coche deportivo se tratase, esto sera lo mas cerca cercano que podras obtener.', 4, 1, 19);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (20, 'Chevrolet Colorado', 'Al combinar excelentes modales en la carretera con un excelente rendimiento todoterreno y facilidad de uso diario, la Chevrolet Colorado se ha convertido en una de las mejores opciones a la hora de elegir una pickup. Esta pickup es para quienes tienen potencia para seguir sin importar el camino y para los que llegan a la cima, pero buscan ir más arriba. Sorpréndete con la Colorado, la más potente de su categoría y no solo por su motor, sino tambien por sus características tecnológicas que superan las expectativas. WiFi integrado con conexión para 7 dispositivos, Radio MYLINK hasta 8”, aire acondicionado con climatizador digital, 4x4 Shift On The Fly, control crucero, mandos al volante, cámara de reversa HD, asiento del conductor con ajuste eléctrico y más.', 4, 1, 20);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (21, 'Renault Sandero', 'El Renault SANDERO es el auto para todo lo que sos y entre todas tus versiones, sos alguien que disfruta del diseño. Empieza cuando lo ves por primera vez. Es más que el perfil, es más que el frente, es un estilo único; es el diseño que hace que quieras subirte y manejarlo. Aún con el auto detenido, es fluido, dinámico y avanzado.', 5, 1, 8);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (22, 'Chrysler Town', 'El Chrysler Town & Country es un gran vehículo para familias que necesitan transportar personas y carga con regularidad. Para obtener el máximo espacio para pasajeros y carga, una minivan es difícil de superar, y las opciones de asientos de Town & Country se encuentran entre las mejores de su clase. Y su manejo controlado convierte la experiencia de conducción en algo muy comodo. Las opciones de entretenimiento incluyen TV en el asiento trasero, reproductores de DVD o DVD / Blu-Ray, un potente estéreo y conectividad para iPod.', 5, 1, 4);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (23, 'Kia Carens', 'El Kia Carens es un vehículo multiusos (MPV) de tamaño medio, ideal para aquellos viajes en familia, donde el numero de asientos y la comodidad priman. El Kia Carens está muy bien equipado con asientos de cuero, navegador por satélite, algunas versiones cuentan con un techo corredizo panorámico y un sistema de estacionamiento automático.', 5, 1, 23);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (24, 'Toyota Sienna', 'La Toyota Sienna es la minivan en la que toda la familia finalmente puede estar de acuerdo gracias a su estilo exterior dinámico, interior refinado y sistema de tracción en las cuatro ruedas (AWD) disponible exclusivo en su clase. Un frontal atrevido con aberturas de rejilla superior e inferior más agresivas le dan a la Sienna su perfil llamativo. Sienna prioriza tu seguridad con Toyota Safety Sense ™ 2.0 (TSS 2.0) estándar, un conjunto de características de seguridad activa diseñadas para protegerte de lo inesperado. Las atractivas superficies de los asientos suaves al tacto, las costuras de contraste premium opcionales y una variedad de características de tecnología avanzada ayudan a que el interior de la Sienna sea lujoso y acogedor.', 5, 1, 24);
INSERT INTO products (product_id, name, description, category_id, city_id, specs_id) VALUES (25, 'Honda Odyssey', 'La Odyssey está lista para emprender aventuras familiares con estilo, con una parrilla negra brillante, faros LED y rines de 19 pulgadas disponibles, el lujo y estilo hacen parte de su ADN. Los niveles de equipamiento superiores cuentan con una aspiradora oculta en el área de carga, un sistema de intercomunicador para que pueda hablar con los pasajeros sin levantar la voz y un sistema de cámara interior, que es útil para vigilar a los ruidosos pasajeros del asiento trasero.', 5, 1, 25);

-- Images of products
INSERT INTO product_images_ids VALUES (1, 24);
INSERT INTO product_images_ids VALUES (1, 25);
INSERT INTO product_images_ids VALUES (1, 26);
INSERT INTO product_images_ids VALUES (1, 27);
INSERT INTO product_images_ids VALUES (1, 133);
INSERT INTO product_images_ids VALUES (1, 134);
INSERT INTO product_images_ids VALUES (1, 135);
INSERT INTO product_images_ids VALUES (1, 136);
INSERT INTO product_images_ids VALUES (1, 137);

INSERT INTO product_images_ids VALUES (2, 52);
INSERT INTO product_images_ids VALUES (2, 53);
INSERT INTO product_images_ids VALUES (2, 54);
INSERT INTO product_images_ids VALUES (2, 55);
INSERT INTO product_images_ids VALUES (2, 168);
INSERT INTO product_images_ids VALUES (2, 169);
INSERT INTO product_images_ids VALUES (2, 170);
INSERT INTO product_images_ids VALUES (2, 171);
INSERT INTO product_images_ids VALUES (2, 172);

INSERT INTO product_images_ids VALUES (3, 68);
INSERT INTO product_images_ids VALUES (3, 69);
INSERT INTO product_images_ids VALUES (3, 70);
INSERT INTO product_images_ids VALUES (3, 71);
INSERT INTO product_images_ids VALUES (3, 193);
INSERT INTO product_images_ids VALUES (3, 194);
INSERT INTO product_images_ids VALUES (3, 195);
INSERT INTO product_images_ids VALUES (3, 196);
INSERT INTO product_images_ids VALUES (3, 197);

INSERT INTO product_images_ids VALUES (4, 64);
INSERT INTO product_images_ids VALUES (4, 65);
INSERT INTO product_images_ids VALUES (4, 66);
INSERT INTO product_images_ids VALUES (4, 67);
INSERT INTO product_images_ids VALUES (4, 183);
INSERT INTO product_images_ids VALUES (4, 184);
INSERT INTO product_images_ids VALUES (4, 185);
INSERT INTO product_images_ids VALUES (4, 186);
INSERT INTO product_images_ids VALUES (4, 187);

INSERT INTO product_images_ids VALUES (5, 40);
INSERT INTO product_images_ids VALUES (5, 41);
INSERT INTO product_images_ids VALUES (5, 42);
INSERT INTO product_images_ids VALUES (5, 43);
INSERT INTO product_images_ids VALUES (5, 153);
INSERT INTO product_images_ids VALUES (5, 154);
INSERT INTO product_images_ids VALUES (5, 155);
INSERT INTO product_images_ids VALUES (5, 156);
INSERT INTO product_images_ids VALUES (5, 157);

INSERT INTO product_images_ids VALUES (6, 92);
INSERT INTO product_images_ids VALUES (6, 93);
INSERT INTO product_images_ids VALUES (6, 94);
INSERT INTO product_images_ids VALUES (6, 95);
INSERT INTO product_images_ids VALUES (6, 218);
INSERT INTO product_images_ids VALUES (6, 219);
INSERT INTO product_images_ids VALUES (6, 220);
INSERT INTO product_images_ids VALUES (6, 221);
INSERT INTO product_images_ids VALUES (6, 222);

INSERT INTO product_images_ids VALUES (7, 48);
INSERT INTO product_images_ids VALUES (7, 49);
INSERT INTO product_images_ids VALUES (7, 50);
INSERT INTO product_images_ids VALUES (7, 51);
INSERT INTO product_images_ids VALUES (7, 163);
INSERT INTO product_images_ids VALUES (7, 164);
INSERT INTO product_images_ids VALUES (7, 165);
INSERT INTO product_images_ids VALUES (7, 166);
INSERT INTO product_images_ids VALUES (7, 167);

INSERT INTO product_images_ids VALUES (8, 120);
INSERT INTO product_images_ids VALUES (8, 121);
INSERT INTO product_images_ids VALUES (8, 122);
INSERT INTO product_images_ids VALUES (8, 123);
INSERT INTO product_images_ids VALUES (8, 243);
INSERT INTO product_images_ids VALUES (8, 244);
INSERT INTO product_images_ids VALUES (8, 245);
INSERT INTO product_images_ids VALUES (8, 246);
INSERT INTO product_images_ids VALUES (8, 247);

INSERT INTO product_images_ids VALUES (9, 32);
INSERT INTO product_images_ids VALUES (9, 33);
INSERT INTO product_images_ids VALUES (9, 34);
INSERT INTO product_images_ids VALUES (9, 35);
INSERT INTO product_images_ids VALUES (9, 143);
INSERT INTO product_images_ids VALUES (9, 144);
INSERT INTO product_images_ids VALUES (9, 145);
INSERT INTO product_images_ids VALUES (9, 146);
INSERT INTO product_images_ids VALUES (9, 147);

INSERT INTO product_images_ids VALUES (10, 76);
INSERT INTO product_images_ids VALUES (10, 77);
INSERT INTO product_images_ids VALUES (10, 78);
INSERT INTO product_images_ids VALUES (10, 79);
INSERT INTO product_images_ids VALUES (10, 198);
INSERT INTO product_images_ids VALUES (10, 199);
INSERT INTO product_images_ids VALUES (10, 200);
INSERT INTO product_images_ids VALUES (10, 201);
INSERT INTO product_images_ids VALUES (10, 202);

INSERT INTO product_images_ids VALUES (11, 20);
INSERT INTO product_images_ids VALUES (11, 21);
INSERT INTO product_images_ids VALUES (11, 22);
INSERT INTO product_images_ids VALUES (11, 23);
INSERT INTO product_images_ids VALUES (11, 128);
INSERT INTO product_images_ids VALUES (11, 129);
INSERT INTO product_images_ids VALUES (11, 130);
INSERT INTO product_images_ids VALUES (11, 131);
INSERT INTO product_images_ids VALUES (11, 132);

INSERT INTO product_images_ids VALUES (12, 44);
INSERT INTO product_images_ids VALUES (12, 45);
INSERT INTO product_images_ids VALUES (12, 46);
INSERT INTO product_images_ids VALUES (12, 47);
INSERT INTO product_images_ids VALUES (12, 158);
INSERT INTO product_images_ids VALUES (12, 159);
INSERT INTO product_images_ids VALUES (12, 160);
INSERT INTO product_images_ids VALUES (12, 161);
INSERT INTO product_images_ids VALUES (12, 162);

INSERT INTO product_images_ids VALUES (13, 60);
INSERT INTO product_images_ids VALUES (13, 61);
INSERT INTO product_images_ids VALUES (13, 62);
INSERT INTO product_images_ids VALUES (13, 63);
INSERT INTO product_images_ids VALUES (13, 178);
INSERT INTO product_images_ids VALUES (13, 179);
INSERT INTO product_images_ids VALUES (13, 180);
INSERT INTO product_images_ids VALUES (13, 181);
INSERT INTO product_images_ids VALUES (13, 182);

INSERT INTO product_images_ids VALUES (14, 80);
INSERT INTO product_images_ids VALUES (14, 81);
INSERT INTO product_images_ids VALUES (14, 82);
INSERT INTO product_images_ids VALUES (14, 83);
INSERT INTO product_images_ids VALUES (14, 203);
INSERT INTO product_images_ids VALUES (14, 204);
INSERT INTO product_images_ids VALUES (14, 205);
INSERT INTO product_images_ids VALUES (14, 206);
INSERT INTO product_images_ids VALUES (14, 207);

INSERT INTO product_images_ids VALUES (15, 116);
INSERT INTO product_images_ids VALUES (15, 117);
INSERT INTO product_images_ids VALUES (15, 118);
INSERT INTO product_images_ids VALUES (15, 119);
INSERT INTO product_images_ids VALUES (15, 238);
INSERT INTO product_images_ids VALUES (15, 239);
INSERT INTO product_images_ids VALUES (15, 240);
INSERT INTO product_images_ids VALUES (15, 241);
INSERT INTO product_images_ids VALUES (15, 242);

INSERT INTO product_images_ids VALUES (16, 88);
INSERT INTO product_images_ids VALUES (16, 89);
INSERT INTO product_images_ids VALUES (16, 90);
INSERT INTO product_images_ids VALUES (16, 91);
INSERT INTO product_images_ids VALUES (16, 213);
INSERT INTO product_images_ids VALUES (16, 214);
INSERT INTO product_images_ids VALUES (16, 215);
INSERT INTO product_images_ids VALUES (16, 216);
INSERT INTO product_images_ids VALUES (16, 217);

INSERT INTO product_images_ids VALUES (17, 108);
INSERT INTO product_images_ids VALUES (17, 109);
INSERT INTO product_images_ids VALUES (17, 110);
INSERT INTO product_images_ids VALUES (17, 111);
INSERT INTO product_images_ids VALUES (17, 228);
INSERT INTO product_images_ids VALUES (17, 229);
INSERT INTO product_images_ids VALUES (17, 230);
INSERT INTO product_images_ids VALUES (17, 231);
INSERT INTO product_images_ids VALUES (17, 232);

INSERT INTO product_images_ids VALUES (18, 84);
INSERT INTO product_images_ids VALUES (18, 85);
INSERT INTO product_images_ids VALUES (18, 86);
INSERT INTO product_images_ids VALUES (18, 87);
INSERT INTO product_images_ids VALUES (18, 208);
INSERT INTO product_images_ids VALUES (18, 209);
INSERT INTO product_images_ids VALUES (18, 210);
INSERT INTO product_images_ids VALUES (18, 211);
INSERT INTO product_images_ids VALUES (18, 212);

INSERT INTO product_images_ids VALUES (19, 124);
INSERT INTO product_images_ids VALUES (19, 125);
INSERT INTO product_images_ids VALUES (19, 126);
INSERT INTO product_images_ids VALUES (19, 127);
INSERT INTO product_images_ids VALUES (19, 248);
INSERT INTO product_images_ids VALUES (19, 249);
INSERT INTO product_images_ids VALUES (19, 250);
INSERT INTO product_images_ids VALUES (19, 251);
INSERT INTO product_images_ids VALUES (19, 258);

INSERT INTO product_images_ids VALUES (20, 28);
INSERT INTO product_images_ids VALUES (20, 29);
INSERT INTO product_images_ids VALUES (20, 30);
INSERT INTO product_images_ids VALUES (20, 31);
INSERT INTO product_images_ids VALUES (20, 138);
INSERT INTO product_images_ids VALUES (20, 139);
INSERT INTO product_images_ids VALUES (20, 140);
INSERT INTO product_images_ids VALUES (20, 141);
INSERT INTO product_images_ids VALUES (20, 142);

INSERT INTO product_images_ids VALUES (21, 100);
INSERT INTO product_images_ids VALUES (21, 101);
INSERT INTO product_images_ids VALUES (21, 102);
INSERT INTO product_images_ids VALUES (21, 103);
INSERT INTO product_images_ids VALUES (21, 223);
INSERT INTO product_images_ids VALUES (21, 224);
INSERT INTO product_images_ids VALUES (21, 225);
INSERT INTO product_images_ids VALUES (21, 226);
INSERT INTO product_images_ids VALUES (21, 227);

INSERT INTO product_images_ids VALUES (22, 36);
INSERT INTO product_images_ids VALUES (22, 37);
INSERT INTO product_images_ids VALUES (22, 38);
INSERT INTO product_images_ids VALUES (22, 39);
INSERT INTO product_images_ids VALUES (22, 148);
INSERT INTO product_images_ids VALUES (22, 149);
INSERT INTO product_images_ids VALUES (22, 150);
INSERT INTO product_images_ids VALUES (22, 151);
INSERT INTO product_images_ids VALUES (22, 152);

INSERT INTO product_images_ids VALUES (23, 72);
INSERT INTO product_images_ids VALUES (23, 73);
INSERT INTO product_images_ids VALUES (23, 74);
INSERT INTO product_images_ids VALUES (23, 75);
INSERT INTO product_images_ids VALUES (23, 188);
INSERT INTO product_images_ids VALUES (23, 189);
INSERT INTO product_images_ids VALUES (23, 190);
INSERT INTO product_images_ids VALUES (23, 191);
INSERT INTO product_images_ids VALUES (23, 192);

INSERT INTO product_images_ids VALUES (24, 112);
INSERT INTO product_images_ids VALUES (24, 113);
INSERT INTO product_images_ids VALUES (24, 114);
INSERT INTO product_images_ids VALUES (24, 115);
INSERT INTO product_images_ids VALUES (24, 233);
INSERT INTO product_images_ids VALUES (24, 234);
INSERT INTO product_images_ids VALUES (24, 235);
INSERT INTO product_images_ids VALUES (24, 236);
INSERT INTO product_images_ids VALUES (24, 247);

INSERT INTO product_images_ids VALUES (25, 56);
INSERT INTO product_images_ids VALUES (25, 57);
INSERT INTO product_images_ids VALUES (25, 58);
INSERT INTO product_images_ids VALUES (25, 59);
INSERT INTO product_images_ids VALUES (25, 173);
INSERT INTO product_images_ids VALUES (25, 174);
INSERT INTO product_images_ids VALUES (25, 175);
INSERT INTO product_images_ids VALUES (25, 176);
INSERT INTO product_images_ids VALUES (25, 177);

-- terms and conditions
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (1, 'Cancelacion', 'Podra cancelar gratis y sin penalización 24 hrs antes de la hora programada para iniciar la reserva, podra hacerlo a través del portal web en la linea telefonica 6325685.', 257);
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (2, 'Gastos Asumido', 'Cualquier daño, multa o penalización alguna producto del usuario titular de la reserva sera asumida en su totalidad economicamente y de completa responsabilidad de este. ', 255);
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (3, 'Documentos Exigidos', 'Recuerde su DNI o Pasaporte a la hora de retirar el vehiculo, y recuerde portar siempre con usted su licencia de conducción valida para las autoridades del país.', 254);
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (4, 'Modificación', 'Modifique su reserva sin penalidad alguna en cualquier momento, bajo los horarios y vehiculos disponibles, no se haran devolucion por reducción del valor de la reserva, y el usuario asumira diferencias de valor.', 256);
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (5, 'Limites de Rodaje', 'Mantenga el vehiculo dentro de las fronteras del territorio nacional, si desea salir de este, debera acercarse a una de nuestras oficinas y seguir el proceso con un asesor.', 258);
INSERT INTO terms_and_conditions (id, title, description, icon_id) VALUES (6, 'Soporte 24/7', 'Comunicate con nuestro soporte telefonico disponible las 24 hrs del dia los 7 dias de la semana, nuestro equipo estara dispuesto a ayudarte ante cualquier eventualidad o asistencia que solicites', 253);

-- terma and conditions relation with products
INSERT INTO products_terms_and_conditions VALUES (1, 1);
INSERT INTO products_terms_and_conditions VALUES (1, 2);
INSERT INTO products_terms_and_conditions VALUES (1, 3);
INSERT INTO products_terms_and_conditions VALUES (1, 4);
INSERT INTO products_terms_and_conditions VALUES (1, 5);
INSERT INTO products_terms_and_conditions VALUES (1, 6);
INSERT INTO products_terms_and_conditions VALUES (2, 1);
INSERT INTO products_terms_and_conditions VALUES (2, 2);
INSERT INTO products_terms_and_conditions VALUES (2, 3);
INSERT INTO products_terms_and_conditions VALUES (2, 4);
INSERT INTO products_terms_and_conditions VALUES (2, 5);
INSERT INTO products_terms_and_conditions VALUES (2, 6);
INSERT INTO products_terms_and_conditions VALUES (3, 1);
INSERT INTO products_terms_and_conditions VALUES (3, 2);
INSERT INTO products_terms_and_conditions VALUES (3, 3);
INSERT INTO products_terms_and_conditions VALUES (3, 4);
INSERT INTO products_terms_and_conditions VALUES (3, 5);
INSERT INTO products_terms_and_conditions VALUES (3, 6);
INSERT INTO products_terms_and_conditions VALUES (4, 1);
INSERT INTO products_terms_and_conditions VALUES (4, 2);
INSERT INTO products_terms_and_conditions VALUES (4, 3);
INSERT INTO products_terms_and_conditions VALUES (4, 4);
INSERT INTO products_terms_and_conditions VALUES (4, 5);
INSERT INTO products_terms_and_conditions VALUES (4, 6);
INSERT INTO products_terms_and_conditions VALUES (5, 1);
INSERT INTO products_terms_and_conditions VALUES (5, 2);
INSERT INTO products_terms_and_conditions VALUES (5, 3);
INSERT INTO products_terms_and_conditions VALUES (5, 4);
INSERT INTO products_terms_and_conditions VALUES (5, 5);
INSERT INTO products_terms_and_conditions VALUES (5, 6);
INSERT INTO products_terms_and_conditions VALUES (6, 1);
INSERT INTO products_terms_and_conditions VALUES (6, 2);
INSERT INTO products_terms_and_conditions VALUES (6, 3);
INSERT INTO products_terms_and_conditions VALUES (6, 4);
INSERT INTO products_terms_and_conditions VALUES (6, 5);
INSERT INTO products_terms_and_conditions VALUES (6, 6);
INSERT INTO products_terms_and_conditions VALUES (7, 1);
INSERT INTO products_terms_and_conditions VALUES (7, 2);
INSERT INTO products_terms_and_conditions VALUES (7, 3);
INSERT INTO products_terms_and_conditions VALUES (7, 4);
INSERT INTO products_terms_and_conditions VALUES (7, 5);
INSERT INTO products_terms_and_conditions VALUES (7, 6);
INSERT INTO products_terms_and_conditions VALUES (8, 1);
INSERT INTO products_terms_and_conditions VALUES (8, 2);
INSERT INTO products_terms_and_conditions VALUES (8, 3);
INSERT INTO products_terms_and_conditions VALUES (8, 4);
INSERT INTO products_terms_and_conditions VALUES (8, 5);
INSERT INTO products_terms_and_conditions VALUES (8, 6);
INSERT INTO products_terms_and_conditions VALUES (9, 1);
INSERT INTO products_terms_and_conditions VALUES (9, 2);
INSERT INTO products_terms_and_conditions VALUES (9, 3);
INSERT INTO products_terms_and_conditions VALUES (9, 4);
INSERT INTO products_terms_and_conditions VALUES (9, 5);
INSERT INTO products_terms_and_conditions VALUES (9, 6);
INSERT INTO products_terms_and_conditions VALUES (10, 1);
INSERT INTO products_terms_and_conditions VALUES (10, 2);
INSERT INTO products_terms_and_conditions VALUES (10, 3);
INSERT INTO products_terms_and_conditions VALUES (10, 4);
INSERT INTO products_terms_and_conditions VALUES (10, 5);
INSERT INTO products_terms_and_conditions VALUES (10, 6);
INSERT INTO products_terms_and_conditions VALUES (11, 1);
INSERT INTO products_terms_and_conditions VALUES (11, 2);
INSERT INTO products_terms_and_conditions VALUES (11, 3);
INSERT INTO products_terms_and_conditions VALUES (11, 4);
INSERT INTO products_terms_and_conditions VALUES (11, 5);
INSERT INTO products_terms_and_conditions VALUES (11, 6);
INSERT INTO products_terms_and_conditions VALUES (12, 1);
INSERT INTO products_terms_and_conditions VALUES (12, 2);
INSERT INTO products_terms_and_conditions VALUES (12, 3);
INSERT INTO products_terms_and_conditions VALUES (12, 4);
INSERT INTO products_terms_and_conditions VALUES (12, 5);
INSERT INTO products_terms_and_conditions VALUES (12, 6);
INSERT INTO products_terms_and_conditions VALUES (13, 1);
INSERT INTO products_terms_and_conditions VALUES (13, 2);
INSERT INTO products_terms_and_conditions VALUES (13, 3);
INSERT INTO products_terms_and_conditions VALUES (13, 4);
INSERT INTO products_terms_and_conditions VALUES (13, 5);
INSERT INTO products_terms_and_conditions VALUES (13, 6);
INSERT INTO products_terms_and_conditions VALUES (14, 1);
INSERT INTO products_terms_and_conditions VALUES (14, 2);
INSERT INTO products_terms_and_conditions VALUES (14, 3);
INSERT INTO products_terms_and_conditions VALUES (14, 4);
INSERT INTO products_terms_and_conditions VALUES (14, 5);
INSERT INTO products_terms_and_conditions VALUES (14, 6);
INSERT INTO products_terms_and_conditions VALUES (15, 1);
INSERT INTO products_terms_and_conditions VALUES (15, 2);
INSERT INTO products_terms_and_conditions VALUES (15, 3);
INSERT INTO products_terms_and_conditions VALUES (15, 4);
INSERT INTO products_terms_and_conditions VALUES (15, 5);
INSERT INTO products_terms_and_conditions VALUES (15, 6);
INSERT INTO products_terms_and_conditions VALUES (16, 1);
INSERT INTO products_terms_and_conditions VALUES (16, 2);
INSERT INTO products_terms_and_conditions VALUES (16, 3);
INSERT INTO products_terms_and_conditions VALUES (16, 4);
INSERT INTO products_terms_and_conditions VALUES (16, 5);
INSERT INTO products_terms_and_conditions VALUES (16, 6);
INSERT INTO products_terms_and_conditions VALUES (17, 1);
INSERT INTO products_terms_and_conditions VALUES (17, 2);
INSERT INTO products_terms_and_conditions VALUES (17, 3);
INSERT INTO products_terms_and_conditions VALUES (17, 4);
INSERT INTO products_terms_and_conditions VALUES (17, 5);
INSERT INTO products_terms_and_conditions VALUES (17, 6);
INSERT INTO products_terms_and_conditions VALUES (18, 1);
INSERT INTO products_terms_and_conditions VALUES (18, 2);
INSERT INTO products_terms_and_conditions VALUES (18, 3);
INSERT INTO products_terms_and_conditions VALUES (18, 4);
INSERT INTO products_terms_and_conditions VALUES (18, 5);
INSERT INTO products_terms_and_conditions VALUES (18, 6);
INSERT INTO products_terms_and_conditions VALUES (19, 1);
INSERT INTO products_terms_and_conditions VALUES (19, 2);
INSERT INTO products_terms_and_conditions VALUES (19, 3);
INSERT INTO products_terms_and_conditions VALUES (19, 4);
INSERT INTO products_terms_and_conditions VALUES (19, 5);
INSERT INTO products_terms_and_conditions VALUES (19, 6);
INSERT INTO products_terms_and_conditions VALUES (20, 1);
INSERT INTO products_terms_and_conditions VALUES (20, 2);
INSERT INTO products_terms_and_conditions VALUES (20, 3);
INSERT INTO products_terms_and_conditions VALUES (20, 4);
INSERT INTO products_terms_and_conditions VALUES (20, 5);
INSERT INTO products_terms_and_conditions VALUES (20, 6);
INSERT INTO products_terms_and_conditions VALUES (21, 1);
INSERT INTO products_terms_and_conditions VALUES (21, 2);
INSERT INTO products_terms_and_conditions VALUES (21, 3);
INSERT INTO products_terms_and_conditions VALUES (21, 4);
INSERT INTO products_terms_and_conditions VALUES (21, 5);
INSERT INTO products_terms_and_conditions VALUES (21, 6);
INSERT INTO products_terms_and_conditions VALUES (22, 1);
INSERT INTO products_terms_and_conditions VALUES (22, 2);
INSERT INTO products_terms_and_conditions VALUES (22, 3);
INSERT INTO products_terms_and_conditions VALUES (22, 4);
INSERT INTO products_terms_and_conditions VALUES (22, 5);
INSERT INTO products_terms_and_conditions VALUES (22, 6);
INSERT INTO products_terms_and_conditions VALUES (23, 1);
INSERT INTO products_terms_and_conditions VALUES (23, 2);
INSERT INTO products_terms_and_conditions VALUES (23, 3);
INSERT INTO products_terms_and_conditions VALUES (23, 4);
INSERT INTO products_terms_and_conditions VALUES (23, 5);
INSERT INTO products_terms_and_conditions VALUES (23, 6);
INSERT INTO products_terms_and_conditions VALUES (24, 1);
INSERT INTO products_terms_and_conditions VALUES (24, 2);
INSERT INTO products_terms_and_conditions VALUES (24, 3);
INSERT INTO products_terms_and_conditions VALUES (24, 4);
INSERT INTO products_terms_and_conditions VALUES (24, 5);
INSERT INTO products_terms_and_conditions VALUES (24, 6);
INSERT INTO products_terms_and_conditions VALUES (25, 1);
INSERT INTO products_terms_and_conditions VALUES (25, 2);
INSERT INTO products_terms_and_conditions VALUES (25, 3);
INSERT INTO products_terms_and_conditions VALUES (25, 4);
INSERT INTO products_terms_and_conditions VALUES (25, 5);
INSERT INTO products_terms_and_conditions VALUES (25, 6);