USE digitalRentcarProducts;

-- Products
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Chevrolet Captiva', 'Captiva Turbo llega para desafiar todas las expectativas de lo que se espera de un SUV. Más allá de su atractivo diseño, tiene el espacio suficiente para todo y todos, gracias a su capacidad para 5 o 7 pasajeros. Está equipada con tecnología superior y atributos avanzados de seguridad.', 18, 1, 1, 1);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Chevrolet Camaro', 'El Chevrolet Camaro ofrece buen nivel de equipamiento y asistencias al conductor para que el viaje en ciudad y carretera sea más seguro, pero no deja de lado sus raíces deportivas y puede liberar todo su potencial cuando uno lo desee. Si eres fanático de los autos americanos, este muscle car es uno de los más fieles a su origen.', 17, 3, 1, 2);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Nissan Frontier', 'Durante generaciones, Nissan ha fabricado las pick ups más confiables, manteniéndose así siempre a la delantera en resistencia y durabilidad. Nissan NP300® está diseñada para satisfacer todas tus necesidades gracias a su motor, capacidad de carga y chasis reforzado ademas de sus extraordinarios ángulos de entrada (28.5°) y salida (23.6°) le permiten enfrentarse sin problema a terrenos inclinados  e inhóspitos.', 23, 4, 1, 3);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Chrysler Town', 'El Chrysler Town & Country es un gran vehículo para familias que necesitan transportar personas y carga con regularidad. Para obtener el máximo espacio para pasajeros y carga, una minivan es difícil de superar, y las opciones de asientos de Town & Country se encuentran entre las mejores de su clase. Y su manejo controlado convierte la experiencia de conducción en algo muy comodo. Las opciones de entretenimiento incluyen TV en el asiento trasero, reproductores de DVD o DVD / Blu-Ray, un potente estéreo y conectividad para iPod.', 19, 1, 1, 4);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Ford Mustang', 'Escucha el rugido de un Mustang cuando el suelo comienza a temblar y las piernas a agitarse. Como siempre, el Mustang invoca su desempeño con características de manejo mejorado, opciones de motor súper potente y diseño de Mustang clásico. El habitáculo del Ford Mustang cuenta con un diseño muy personal que aboga por las líneas curvas y la profusión de botones e interruptores, recordando enormemente a los salpicaderos que el propio Mustang ofrecía en los años 60 y 70.', 20, 3, 1, 5);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Honda CRVs', 'Diseñado para llevarte más lejos, El CR-V ofrece millas y millas de diversión al conducir, con tracción total, 212 caballos de fuerza en total del sistema, y con mucho espacio de carga. Su exterior deportivo cuenta con líneas esculpidas y rines de aleación de 19 pulgadas disponibles, mientras que su espacio interior ofrece uun volante con calefacción disponible, asientos tapizados en cuero y otros materiales premium.', 22, 1, 1, 6);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Nissan Versa', 'El sedán Nissan Versa es una excelente herramienta de transporte para llevar a los pasajeros del punto A al punto B, pero también hace que el viaje sea más agradable que muchos otros autos subcompactos. El Nissan no solo es atractivo, su motor de cuatro cilindros tiene una economía de combustible en las carreteras impresionante. El suave andar del Versa y los cómodos asientos delanteros lo convierten en un carro relajante para los desplazamientos diarios, y está disponible con más asistencia al conductor que sus compañeros de clase.', 24, 2, 1, 7);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Renault Sandero', 'El Renault SANDERO es el auto para todo lo que sos y entre todas tus versiones, sos alguien que disfruta del diseño. Empieza cuando lo ves por primera vez. Es más que el perfil, es más que el frente, es un estilo único; es el diseño que hace que quieras subirte y manejarlo. Aún con el auto detenido, es fluido, dinámico y avanzado.', 26, 1, 1, 8);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Toyota Hilux', 'Bajo la musculosa y gran carrocería del Hilux se esconde un chasis tradicional de pick-up y vehículo todoterreno. Se trata de una plataforma de largueros y travesaños con suspensión trasera de ballesta diseñada especialmente para soportar grandes cargas, una gran capacidad off-road y una elevada versatilidad de carrocerías. La capacidad de carga de la caja permite hasta 1.040 kilogramos de carga. En función de la cabina puede albergar entre dos y cinco pasajeros, y en cuanto a cotas todoterreno ofrece 27 grados de ángulo de entrada, 27 grados de ángulo de salida y 23 grados de ángulo ventral con una profundidad de vadeo de hasta 70 centímetros con una altura libre de 29,3 centrímetros.', 28, 4, 1, 9);
INSERT INTO products (name, description, main_image_id, category_id, city_id, specs_id) VALUES ('Toyota Vios', 'Toyota ha declarado explícitamente que, con el modelo Toyota Vios, se han propuesto conservar las mejores cualidades que los clientes han llegado a conocer, amar, a saber, la calidad y la comodidad. Fieles a su palabra, parecen estar en el camino correcto con la nueva generación. más equipamiento, un interior más refinado y una caja de cambios completamente nueva, son propiedades del nuevo Toyota Vios, disponible en nuestras vitrinas.', 29, 2, 1, 10);

-- Images of products
INSERT INTO product_images_ids VALUES (1, 35);
INSERT INTO product_images_ids VALUES (1, 36);
INSERT INTO product_images_ids VALUES (1, 37);
INSERT INTO product_images_ids VALUES (1, 38);
INSERT INTO product_images_ids VALUES (1, 39);
INSERT INTO product_images_ids VALUES (2, 30);
INSERT INTO product_images_ids VALUES (2, 31);
INSERT INTO product_images_ids VALUES (2, 32);
INSERT INTO product_images_ids VALUES (2, 33);
INSERT INTO product_images_ids VALUES (2, 34);
INSERT INTO product_images_ids VALUES (3, 60);
INSERT INTO product_images_ids VALUES (3, 61);
INSERT INTO product_images_ids VALUES (3, 62);
INSERT INTO product_images_ids VALUES (3, 63);
INSERT INTO product_images_ids VALUES (3, 64);
INSERT INTO product_images_ids VALUES (4, 40);
INSERT INTO product_images_ids VALUES (4, 41);
INSERT INTO product_images_ids VALUES (4, 42);
INSERT INTO product_images_ids VALUES (4, 43);
INSERT INTO product_images_ids VALUES (4, 44);
INSERT INTO product_images_ids VALUES (5, 45);
INSERT INTO product_images_ids VALUES (5, 46);
INSERT INTO product_images_ids VALUES (5, 47);
INSERT INTO product_images_ids VALUES (5, 48);
INSERT INTO product_images_ids VALUES (5, 49);
INSERT INTO product_images_ids VALUES (6, 55);
INSERT INTO product_images_ids VALUES (6, 56);
INSERT INTO product_images_ids VALUES (6, 57);
INSERT INTO product_images_ids VALUES (6, 58);
INSERT INTO product_images_ids VALUES (6, 59);
INSERT INTO product_images_ids VALUES (7, 65);
INSERT INTO product_images_ids VALUES (7, 66);
INSERT INTO product_images_ids VALUES (7, 67);
INSERT INTO product_images_ids VALUES (7, 68);
INSERT INTO product_images_ids VALUES (7, 69);
INSERT INTO product_images_ids VALUES (8, 70);
INSERT INTO product_images_ids VALUES (8, 71);
INSERT INTO product_images_ids VALUES (8, 72);
INSERT INTO product_images_ids VALUES (8, 73);
INSERT INTO product_images_ids VALUES (8, 74);
INSERT INTO product_images_ids VALUES (9, 75);
INSERT INTO product_images_ids VALUES (9, 76);
INSERT INTO product_images_ids VALUES (9, 77);
INSERT INTO product_images_ids VALUES (9, 78);
INSERT INTO product_images_ids VALUES (9, 79);
INSERT INTO product_images_ids VALUES (10, 80);
INSERT INTO product_images_ids VALUES (10, 81);
INSERT INTO product_images_ids VALUES (10, 82);
INSERT INTO product_images_ids VALUES (10, 83);
INSERT INTO product_images_ids VALUES (10, 84);