version: '3.9'

networks:
  networkBackend:

services:
  config-server:
    image: "juanrojasc/digitalrentcar-config-server"
    networks:
      - networkBackend
    ports:
      - 9296:9296
  eureka-service:
    image: "juanrojasc/digitalrentcar-eureka-service"
    networks:
      - networkBackend
    ports:
      - 8761:8761
    depends_on:
      - config-server
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
    command: "./wait-for-it.sh config-server:9296 --strict --timeout=0 -- java -jar eureka-service.jar"
    restart: always
  images-service:
    image: "juanrojasc/digitalrentcar-images-service"
    networks:
      - networkBackend
    ports:
      - 9005:9005
    depends_on:
      eureka-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarImages
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh eureka-service:8761 --strict --timeout=0 -- java -jar images-service.jar"
    restart: always
  features-service:
    image: "juanrojasc/digitalrentcar-features-service"
    networks:
      - networkBackend
    ports:
      - 9004:9004
    depends_on:
      images-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarFeatures
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh images-service:9005 --strict --timeout=0 -- java -jar features-service.jar"
    restart: always
  specs-service:
    image: "juanrojasc/digitalrentcar-specs-service"
    networks:
      - networkBackend
    ports:
      - 9003:9003
    depends_on:
      features-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarSpecs
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh features-service:9004 --strict --timeout=0 -- java -jar specs-service.jar"
    restart: always
  cities-service:
    image: "juanrojasc/digitalrentcar-cities-service"
    networks:
      - networkBackend
    ports:
      - 9002:9002
    depends_on:
      specs-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarCities
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh specs-service:9003 --strict --timeout=0 -- java -jar cities-service.jar"
    restart: always
  categories-service:
    image: "juanrojasc/digitalrentcar-categories-service"
    networks:
      - networkBackend
    ports:
      - 9001:9001
    depends_on:
      cities-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarCategories
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh cities-service:9002 --strict --timeout=0 -- java -jar categories-service.jar"
    restart: always
  users-service:
    image: "juanrojasc/digitalrentcar-users-service"
    networks:
      - networkBackend
    ports:
      - 9006:9006
    depends_on:
      categories-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarUsers
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOCALHOST=${LOCALHOST}
    command: "./wait-for-it.sh categories-service:9001 --strict --timeout=0 -- java -jar users-service.jar"
    restart: always
  products-service:
    image: "juanrojasc/digitalrentcar-products-service"
    networks:
      - networkBackend
    ports:
      - 9000:9000
    depends_on:
      categories-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_LINK_CONNECTION=${DB_LINK_CONNECTION}/digitalRentcarProducts
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    command: "./wait-for-it.sh users-service:9006 --strict --timeout=0 -- java -jar products-service.jar"
    restart: always
  gateway-service:
    image: "juanrojasc/digitalrentcar-gateway-service"
    networks:
      - networkBackend
    ports:
      - 80:8080
    depends_on:
      products-service:
        condition: service_started
    environment:
      - CONFIG_SERVER=${CONFIG_SERVER}
      - EUREKA_SERVER=${EUREKA_SERVER}
    command: "./wait-for-it.sh products-service:9000 --strict --timeout=0 -- java -jar gateway-service.jar"
    restart: always